name: Keep The Streamlit App Alive

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

jobs:
  ping-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to lemons.streamlit.app
        run: curl -s -o /dev/null -w "%{http_code}\n" https://lemons.streamlit.app/
